! This file was originally generated by cart, but then manually edited. 
! DO NOT REGENERATE THIS FILE!
program main
    use iso_c_binding, only : c_bool
    use iso_fortran_env, only : OUTPUT_UNIT, ERROR_UNIT
    use prif, only : &
        prif_stop &
       ,prif_error_stop
    implicit none

    logical(kind=c_bool), parameter :: false = .false._c_bool

    if (.not.run()) call prif_error_stop(quiet=false, stop_code_char = "Unit tests failed to run")

    call prif_stop(quiet=false)

contains
    function run() result(passed)
        use a00_caffeinate_test, only: &
                check_caffeination, &
                a00_caffeinate_caffeinate => &
                    test_caffeinate
        use caf_allocate_test, only: &
                caf_allocate_prif_allocate => &
                    test_prif_allocate
        use caf_co_broadcast_test, only: &
                caf_co_broadcast_prif_co_broadcast => &
                    test_prif_co_broadcast
        use caf_co_max_test, only: &
                caf_co_max_prif_co_max => &
                    test_prif_co_max
        use caf_co_min_test, only: &
                caf_co_min_prif_co_min => &
                    test_prif_co_min
        use caf_co_reduce_test, only: &
                caf_co_reduce_prif_co_reduce => &
                    test_prif_co_reduce
        use caf_co_sum_test, only: &
                caf_co_sum_prif_co_sum => &
                    test_prif_co_sum
        use caf_coarray_inquiry_test, only: &
                caf_coarray_inquiry_coarray_inquiry => &
                    test_coarray_inquiry
        use caf_image_index_test, only: &
                caf_image_index_prif_image_index => &
                    test_prif_image_index
        use caf_num_images_test, only: &
                caf_num_images_prif_num_images => &
                    test_prif_num_images
        use caf_image_queries_test, only: test_prif_image_queries
        use caf_sync_images_test, only: test_prif_sync_images
        use caf_rma_test, only: &
                caf_rma_prif_rma => &
                    test_prif_rma
        use caf_strided_test, only: &
                    test_prif_rma_strided
        use caf_event_test, only: &
                    test_prif_event
        use caf_teams_test, only: &
                caf_teams_caf_teams => &
                    test_caf_teams
        use caf_this_image_test, only: &
                caf_this_image_prif_this_image_no_coarray => &
                    test_prif_this_image_no_coarray
        use caf_stop_test, only: test_prif_stop
        use caf_error_stop_test, only: test_prif_error_stop
        use veggies, only: test_item_t, test_that, run_tests, result_t



        logical :: passed

        type(test_item_t) :: tests
        type(test_item_t), allocatable :: individual_tests(:)
        type(result_t) :: dummy

        ! ensure an early call to prif_init
        dummy = check_caffeination()

        allocate(individual_tests(0))

#if __flang__ && 0 /* currently no disabled tests */
    block
        integer :: major, minor
#     if defined(__flang_major__) && defined(__flang_minor__)
        major = __flang_major__
        minor = __flang_minor__
#     else
        major = -1
        minor = -1
#     endif
        print *, "-----------------------------------------------------------------"
        print *, "WARNING: flang-new compiler detected, version:",major,".",minor
        print *, "WARNING: Skipping tests that are known to fail with this compiler"
        print *, "-----------------------------------------------------------------"
        call flush(OUTPUT_UNIT)
    end block
#endif
        individual_tests = [a00_caffeinate_caffeinate()]
        individual_tests = [individual_tests, caf_allocate_prif_allocate()]
        individual_tests = [individual_tests, caf_coarray_inquiry_coarray_inquiry()]
        individual_tests = [individual_tests, caf_co_broadcast_prif_co_broadcast()]
        individual_tests = [individual_tests, caf_co_max_prif_co_max()]
        individual_tests = [individual_tests, caf_co_min_prif_co_min()]
        individual_tests = [individual_tests, caf_co_reduce_prif_co_reduce()]
        individual_tests = [individual_tests, caf_co_sum_prif_co_sum()]
        individual_tests = [individual_tests, caf_image_index_prif_image_index()]
        individual_tests = [individual_tests, caf_num_images_prif_num_images()]
        individual_tests = [individual_tests, test_prif_image_queries()]
        individual_tests = [individual_tests, caf_rma_prif_rma()]
        individual_tests = [individual_tests, test_prif_rma_strided()]
        individual_tests = [individual_tests, caf_teams_caf_teams()]
        individual_tests = [individual_tests, caf_this_image_prif_this_image_no_coarray()]
        individual_tests = [individual_tests, test_prif_event()]
        individual_tests = [individual_tests, test_prif_sync_images()]
        individual_tests = [individual_tests, test_prif_stop()]
        individual_tests = [individual_tests, test_prif_error_stop()]

        tests = test_that(individual_tests)

        call flush(OUTPUT_UNIT)
        call flush(ERROR_UNIT)

        passed = run_tests(tests)

    end function
end program
