! Generated by cart. DO NOT EDIT
program main
    implicit none

    if (.not.run()) stop 1
contains
    function run() result(passed)
        use a00_caffeinate_test, only: &
                a00_caffeinate_caffeinate => &
                    test_caffeinate
        use caf_allocate_test, only: &
                caf_allocate_prif_allocate => &
                    test_prif_allocate
        use caf_co_broadcast_test, only: &
                caf_co_broadcast_prif_co_broadcast => &
                    test_prif_co_broadcast
        use caf_co_max_test, only: &
                caf_co_max_prif_co_max => &
                    test_prif_co_max
        use caf_co_min_test, only: &
                caf_co_min_prif_co_min => &
                    test_prif_co_min
        use caf_co_reduce_test, only: &
                caf_co_reduce_prif_co_reduce => &
                    test_prif_co_reduce
        use caf_co_sum_test, only: &
                caf_co_sum_prif_co_sum => &
                    test_prif_co_sum
        use caf_error_stop_test, only: &
                caf_error_stop_prif_this_image => &
                    test_prif_this_image
        use caf_image_index_test, only: &
                caf_image_index_prif_image_index => &
                    test_prif_image_index
        use caf_num_images_test, only: &
                caf_num_images_prif_num_images => &
                    test_prif_num_images
        use caf_rma_test, only: &
                caf_rma_prif_rma => &
                    test_prif_rma
        use caf_stop_test, only: &
                caf_stop_prif_this_image => &
                    test_prif_this_image
        use caf_this_image_test, only: &
                caf_this_image_prif_this_image => &
                    test_prif_this_image
        use veggies, only: test_item_t, test_that, run_tests



        logical :: passed

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(13)

        individual_tests(1) = a00_caffeinate_caffeinate()
        individual_tests(2) = caf_allocate_prif_allocate()
        individual_tests(3) = caf_co_broadcast_prif_co_broadcast()
        individual_tests(4) = caf_co_max_prif_co_max()
        individual_tests(5) = caf_co_min_prif_co_min()
        individual_tests(6) = caf_co_reduce_prif_co_reduce()
        individual_tests(7) = caf_co_sum_prif_co_sum()
        individual_tests(8) = caf_error_stop_prif_this_image()
        individual_tests(9) = caf_image_index_prif_image_index()
        individual_tests(10) = caf_num_images_prif_num_images()
        individual_tests(11) = caf_rma_prif_rma()
        individual_tests(12) = caf_stop_prif_this_image()
        individual_tests(13) = caf_this_image_prif_this_image()
        tests = test_that(individual_tests)


        passed = run_tests(tests)

    end function
end program
