as_character – Caffeine
as_character Module Procedure
60 statements
Source File
module procedure as_character pure module module function as_character(self) result(character_self) Interface →
Arguments
Type Intent Optional Attributes Name
class(intrinsic_array_t), intent(in) :: self
Return Value character(len=:),allocatable
Calls
Called by
Contents
None
Call graph
as_character calls prif_error_stop, as_character
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string