as_int – Caffeine
as_int Function
7 statements
Source File
pure function as_int(ptr)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: ptr
Return Value integer(kind=c_intptr_t)
Called by
Contents
None
Call graph
prif_allocate_coarray calls as_int, caf_establish_child_heap, prif_allocate_coarray
caf_establish_child_heap calls as_int
prif_change_team calls caf_establish_child_heap, prif_change_team
prif_form_team calls caf_establish_child_heap, prif_form_team
prif_deallocate_coarray calls caf_establish_child_heap, prif_deallocate_coarray
prif_end_team calls prif_deallocate_coarray, prif_end_team