assert – Caffeine
assert Module Procedure
54 statements
Source File
module procedure assert module module subroutine assert(assertion, description, diagnostic_data) Interface →
Uses
program_termination_m
caffeine_characterizable_m
image_queries_m
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: assertion
Most assertions will be expressions such as i>0
character(len=*), intent(in) :: description
A brief statement of what is being asserted such as "i>0" or "positive i"
class(*), intent(in), optional :: diagnostic_data
Data to include in an error ouptput: may be of an intrinsic type or a type that extends characterizable_t
Calls
Called by
Contents
None
Call graph
assert calls prif_error_stop, assert
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string
prif_base_pointer calls assert, prif_base_pointer
prif_co_reduce calls assert, prif_co_reduce
prif_get calls prif_base_pointer, prif_get
prif_put calls prif_base_pointer, prif_put
prif_co_min calls prif_co_reduce, prif_co_min
prif_co_max calls prif_co_reduce, prif_co_max