base_pointer – Caffeine
base_pointer Subroutine
9 statements
Source File
subroutine base_pointer(coarray_handle, image_num, ptr)
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_int), intent(in) :: image_num
integer(kind=c_intptr_t), intent(out) :: ptr
Calls
Called by
Contents
None
Call graph
base_pointer calls prif_num_images, caf_convert_base_addr, assert
prif_num_images calls prif_num_images, caf_num_images
assert calls assert, prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate
prif_get calls base_pointer, prif_get
prif_put calls base_pointer, prif_put