caf_co_reduce – Caffeine
caf_co_reduce Module Procedure
168 statements
Source File
module procedure caf_co_reduce module module subroutine caf_co_reduce(a, operation, result_image, stat, errmsg) Interface →
Arguments
Type Intent Optional Attributes Name
type(*), intent(inout), contiguous, target :: a(..)
type(c_funptr), value :: operation
integer, intent(in), optional target :: result_image
integer, intent(out), optional target :: stat
character(len=*), intent(inout), optional target :: errmsg
Calls
Called by
Contents
None
Call graph
caf_co_reduce calls optional_value, caf_error_stop, get_c_ptr, caf_c_same_cfi_type, caf_c_elem_len, assert, get_c_ptr_character, caf_c_co_reduce, caf_c_is_f_string, caf_co_reduce
assert calls assert, caf_error_stop
caf_co_max calls caf_co_reduce, caf_co_max
caf_co_min calls caf_co_reduce, caf_co_min