caf_establish_child_heap – Caffeine
caf_establish_child_heap Subroutine
7 statements
Source File
subroutine caf_establish_child_heap()
Arguments
None
Calls
Called by
Contents
None
Call graph
caf_establish_child_heap calls caf_allocate_remaining, as_int, prif_co_broadcast
prif_co_broadcast calls prif_co_broadcast, caf_co_broadcast
prif_allocate_coarray calls caf_establish_child_heap, prif_allocate_coarray
prif_change_team calls caf_establish_child_heap, prif_change_team
prif_deallocate_coarray calls caf_establish_child_heap, prif_deallocate_coarray
prif_form_team calls caf_establish_child_heap, prif_form_team
prif_end_team calls prif_deallocate_coarray, prif_end_team