caf_co_min – Caffeine
caf_co_min Module Procedure
24 statements
Source File
module procedure caf_co_min module module subroutine caf_co_min(a, result_image, stat, errmsg) Interface →
Arguments
Type Intent Optional Attributes Name
type(*), intent(inout), contiguous, target :: a(..)
integer, intent(in), optional target :: result_image
integer, intent(out), optional target :: stat
character(len=*), intent(inout), optional target :: errmsg
Calls
Called by
Contents
None
Call graph
caf_co_min calls caf_c_numeric_type, optional_value, caf_error_stop, caf_c_is_f_string, get_c_ptr_character, get_c_ptr, caf_c_co_min, caf_co_reduce, caf_co_min
caf_co_reduce calls caf_co_reduce, optional_value, caf_error_stop, caf_c_is_f_string, get_c_ptr_character, get_c_ptr, assert, caf_c_elem_len, caf_c_same_cfi_type, caf_c_co_reduce
assert calls assert, caf_error_stop