caf_co_sum – Caffeine
caf_co_sum Module Procedure
11 statements
Source File
module procedure caf_co_sum module module subroutine caf_co_sum(a, result_image, stat, errmsg) Interface →
Arguments
Type Intent Optional Attributes Name
type(*), intent(inout), contiguous, target :: a(..)
integer, intent(in), optional target :: result_image
integer, intent(out), optional target :: stat
character(len=*), intent(inout), optional target :: errmsg
Calls
Called by
Contents
None
Call graph
caf_co_sum calls get_c_ptr, caf_c_co_sum, optional_value, get_c_ptr_character, caf_co_sum