coarray_handle_check – Caffeine
coarray_handle_check Function
15 statements
Source File
impure elemental function coarray_handle_check(coarray_handle) result(result_)
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handle
Return Value logical
Calls
Called by
Contents
None
Call graph
coarray_handle_check calls assert_always
base_pointer calls coarray_handle_check
prif_ucobound_with_dim calls coarray_handle_check, prif_ucobound_with_dim
prif_size_bytes calls coarray_handle_check, prif_size_bytes
prif_alias_create calls coarray_handle_check, prif_alias_create
prif_lcobound_with_dim calls coarray_handle_check, prif_lcobound_with_dim
prif_coshape calls coarray_handle_check, prif_coshape
prif_get calls coarray_handle_check, base_pointer, prif_get
prif_set_context_data calls coarray_handle_check, prif_set_context_data
prif_ucobound_no_dim calls coarray_handle_check, prif_ucobound_no_dim
prif_alias_destroy calls coarray_handle_check, prif_alias_destroy
prif_image_index_with_team_number calls coarray_handle_check, prif_image_index_with_team_number
prif_lcobound_no_dim calls coarray_handle_check, prif_lcobound_no_dim
prif_put calls coarray_handle_check, base_pointer, prif_put
prif_deallocate_coarray calls coarray_handle_check, prif_deallocate_coarray
prif_allocate_coarray calls coarray_handle_check, prif_allocate_coarray
prif_get_context_data calls coarray_handle_check, prif_get_context_data
prif_this_image_with_dim calls coarray_handle_check, prif_this_image_with_dim
prif_get_strided calls coarray_handle_check, base_pointer, prif_get_strided
prif_image_index calls coarray_handle_check, prif_image_index
prif_image_index_with_team calls coarray_handle_check, prif_image_index_with_team
prif_put_strided calls coarray_handle_check, base_pointer, prif_put_strided
prif_this_image_with_coarray calls coarray_handle_check, prif_this_image_with_coarray
prif_local_data_pointer calls coarray_handle_check, prif_local_data_pointer
prif_end_team calls prif_deallocate_coarray, prif_end_team