f_c_string – Caffeine
f_c_string Function
8 statements
Source File
pure function f_c_string(f_string) result(c_string)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: f_string
Return Value character(kind=c_char,len=1)(len(f_string))
Called by
Contents
None
Call graph
prif_error_stop_character calls f_c_string
prif_error_stop calls prif_error_stop_character, prif_error_stop
unimplemented calls prif_error_stop
prif_co_min calls prif_error_stop, prif_co_reduce, prif_co_min
assert calls prif_error_stop, assert
prif_co_max calls prif_error_stop, prif_co_reduce, prif_co_max
prif_co_reduce calls prif_error_stop, assert, prif_co_reduce
prif_deallocate_coarray calls prif_error_stop, prif_deallocate_coarray
prif_atomic_fetch_and calls unimplemented, prif_atomic_fetch_and
prif_failed_images calls unimplemented, prif_failed_images
prif_ucobound_with_dim calls unimplemented, prif_ucobound_with_dim
prif_put_strided_with_notify calls unimplemented, prif_put_strided_with_notify
prif_atomic_define_int_indirect calls unimplemented, prif_atomic_define_int_indirect
prif_atomic_ref_logical_indirect calls unimplemented, prif_atomic_ref_logical_indirect
prif_num_images_with_team calls unimplemented, prif_num_images_with_team
prif_event_post calls unimplemented, prif_event_post
prif_put_indirect_with_notify_indirect calls unimplemented, prif_put_indirect_with_notify_indirect
prif_team_number calls unimplemented, prif_team_number
prif_atomic_cas_int calls unimplemented, prif_atomic_cas_int
prif_atomic_or calls unimplemented, prif_atomic_or
prif_lcobound_no_dim calls unimplemented, prif_lcobound_no_dim
prif_atomic_fetch_and_indirect calls unimplemented, prif_atomic_fetch_and_indirect
prif_form_team calls unimplemented, prif_form_team
prif_put_strided_with_notify_indirect calls unimplemented, prif_put_strided_with_notify_indirect
prif_unlock calls unimplemented, prif_unlock
prif_atomic_define_logical calls unimplemented, prif_atomic_define_logical
prif_atomic_xor calls unimplemented, prif_atomic_xor
prif_get_context_data calls unimplemented, prif_get_context_data
prif_num_images_with_team_number calls unimplemented, prif_num_images_with_team_number
prif_event_post_indirect calls unimplemented, prif_event_post_indirect
prif_image_index_with_team calls unimplemented, prif_image_index_with_team
prif_put_strided calls unimplemented, prif_put_strided
prif_alias_destroy calls unimplemented, prif_alias_destroy
prif_atomic_cas_int_indirect calls unimplemented, prif_atomic_cas_int_indirect
prif_atomic_or_indirect calls unimplemented, prif_atomic_or_indirect
prif_lcobound_with_dim calls unimplemented, prif_lcobound_with_dim
prif_stopped_images calls unimplemented, prif_stopped_images
prif_atomic_add calls unimplemented, prif_atomic_add
prif_atomic_fetch_or calls unimplemented, prif_atomic_fetch_or
prif_put_with_notify calls unimplemented, prif_put_with_notify
prif_unlock_indirect calls unimplemented, prif_unlock_indirect
prif_atomic_define_logical_indirect calls unimplemented, prif_atomic_define_logical_indirect
prif_atomic_xor_indirect calls unimplemented, prif_atomic_xor_indirect
prif_event_query calls unimplemented, prif_event_query
prif_image_index_with_team_number calls unimplemented, prif_image_index_with_team_number
prif_put_strided_indirect calls unimplemented, prif_put_strided_indirect
prif_this_image_with_coarray calls unimplemented, prif_this_image_with_coarray
prif_atomic_cas_logical calls unimplemented, prif_atomic_cas_logical
prif_atomic_ref_int calls unimplemented, prif_atomic_ref_int
prif_coshape calls unimplemented, prif_coshape
prif_lock calls unimplemented, prif_lock
prif_get_strided calls unimplemented, prif_get_strided
prif_sync_images calls unimplemented, prif_sync_images
prif_atomic_add_indirect calls unimplemented, prif_atomic_add_indirect
prif_atomic_fetch_or_indirect calls unimplemented, prif_atomic_fetch_or_indirect
prif_put_with_notify_indirect calls unimplemented, prif_put_with_notify_indirect
prif_atomic_fetch_add calls unimplemented, prif_atomic_fetch_add
prif_change_team calls unimplemented, prif_change_team
prif_event_wait calls unimplemented, prif_event_wait
prif_image_status calls unimplemented, prif_image_status
prif_put_strided_indirect_with_notify calls unimplemented, prif_put_strided_indirect_with_notify
prif_this_image_with_dim calls unimplemented, prif_this_image_with_dim
prif_alias_create calls unimplemented, prif_alias_create
prif_atomic_cas_logical_indirect calls unimplemented, prif_atomic_cas_logical_indirect
prif_atomic_ref_int_indirect calls unimplemented, prif_atomic_ref_int_indirect
prif_critical calls unimplemented, prif_critical
prif_lock_indirect calls unimplemented, prif_lock_indirect
prif_end_critical calls unimplemented, prif_end_critical
prif_get_strided_indirect calls unimplemented, prif_get_strided_indirect
prif_sync_memory calls unimplemented, prif_sync_memory
prif_atomic_and calls unimplemented, prif_atomic_and
prif_atomic_fetch_xor calls unimplemented, prif_atomic_fetch_xor
prif_set_context_data calls unimplemented, prif_set_context_data
prif_atomic_fetch_add_indirect calls unimplemented, prif_atomic_fetch_add_indirect
prif_put_indirect_with_notify calls unimplemented, prif_put_indirect_with_notify
prif_fail_image calls unimplemented, prif_fail_image
prif_put_strided_indirect_with_notify_indirect calls unimplemented, prif_put_strided_indirect_with_notify_indirect
prif_ucobound_no_dim calls unimplemented, prif_ucobound_no_dim
prif_atomic_define_int calls unimplemented, prif_atomic_define_int
prif_atomic_ref_logical calls unimplemented, prif_atomic_ref_logical
prif_notify_wait calls unimplemented, prif_notify_wait
prif_end_team calls unimplemented, prif_end_team
prif_get_team calls unimplemented, prif_get_team
prif_sync_team calls unimplemented, prif_sync_team
prif_atomic_and_indirect calls unimplemented, prif_atomic_and_indirect
prif_atomic_fetch_xor_indirect calls unimplemented, prif_atomic_fetch_xor_indirect
prif_size_bytes calls unimplemented, prif_size_bytes
base_pointer calls assert
prif_get calls base_pointer, prif_get
prif_put calls base_pointer, prif_put