get_c_ptr – Caffeine
get_c_ptr Function
9 statements
Source File
public pure function get_c_ptr(stat) result(ptr)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional target :: stat
Return Value type(c_ptr)
Called by
Contents
None
Call graph
prif_co_sum calls get_c_ptr, prif_co_sum
prif_co_reduce calls get_c_ptr, prif_co_reduce
prif_co_broadcast calls get_c_ptr, prif_co_broadcast
prif_co_min calls get_c_ptr, prif_co_reduce, prif_co_min
prif_co_max calls get_c_ptr, prif_co_reduce, prif_co_max
prif_allocate calls prif_co_sum, prif_allocate