get_c_ptr_character – Caffeine
get_c_ptr_character Function
9 statements
Source File
public pure function get_c_ptr_character(errmsg) result(ptr)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional target :: errmsg
Return Value type(c_ptr)
Called by
Contents
None
Call graph
prif_co_sum calls get_c_ptr_character, prif_co_sum
prif_co_reduce calls get_c_ptr_character, prif_co_reduce
prif_co_min calls get_c_ptr_character, prif_co_reduce, prif_co_min
prif_co_max calls get_c_ptr_character, prif_co_reduce, prif_co_max
prif_allocate calls prif_co_sum, prif_allocate