optional_value – Caffeine
optional_value Function
9 statements
Source File
pure function optional_value(var) result(c_val)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: var
Return Value integer(kind=c_int)
Called by
Contents
None
Call graph
prif_co_sum calls optional_value, prif_co_sum
prif_co_max calls optional_value, prif_co_reduce, prif_co_max
prif_co_reduce calls optional_value, prif_co_reduce
prif_co_min calls optional_value, prif_co_reduce, prif_co_min
prif_allocate_coarray calls prif_co_sum, prif_allocate_coarray