prif_form_team – Caffeine
prif_form_team Module Procedure
20 statements
Source File
module procedure prif_form_team module module subroutine prif_form_team(team_number, team, new_index, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int64_t), intent(in) :: team_number
type(prif_team_type), intent(out) :: team
integer(kind=c_int), intent(in), optional :: new_index
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_form_team calls caf_num_images, caf_establish_child_heap, caf_this_image, caf_form_team, caf_have_child_teams, prif_form_team
caf_establish_child_heap calls caf_allocate_remaining, prif_co_broadcast, as_int
prif_co_broadcast calls prif_co_broadcast, caf_co_broadcast