prif_get_strided – Caffeine
prif_get_strided Module Procedure
6 statements
Source File
module procedure prif_get_strided module module subroutine prif_get_strided(image_num, coarray_handle, offset, remote_stride, current_image_buffer, current_image_stride, element_size, extent, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_size_t), intent(in) :: offset
integer(kind=c_ptrdiff_t), intent(in) :: remote_stride(:)
type(c_ptr), intent(in) :: current_image_buffer
integer(kind=c_ptrdiff_t), intent(in) :: current_image_stride(:)
integer(kind=c_size_t), intent(in) :: element_size
integer(kind=c_size_t), intent(in) :: extent(:)
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_get_strided calls call_assert, base_pointer, coarray_handle_check, prif_get_strided_indirect, prif_get_strided
base_pointer calls call_assert, coarray_handle_check, caf_convert_base_addr, call_assert_describe
coarray_handle_check calls assert_always
prif_get_strided_indirect calls prif_get_strided_indirect, get_strided_helper
get_strided_helper calls call_assert, caf_get_strided