prif_get_raw_strided – Caffeine
prif_get_raw_strided Module Procedure
3 statements
Source File
module procedure prif_get_raw_strided module module subroutine prif_get_raw_strided(image_num, local_buffer, remote_ptr, element_size, extent, remote_ptr_stride, local_buffer_stride, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
type(c_ptr), intent(in) :: local_buffer
integer(kind=c_intptr_t), intent(in) :: remote_ptr
integer(kind=c_size_t), intent(in) :: element_size
integer(kind=c_size_t), intent(in) :: extent(:)
integer(kind=c_ptrdiff_t), intent(in) :: remote_ptr_stride(:)
integer(kind=c_ptrdiff_t), intent(in) :: local_buffer_stride(:)
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_get_raw_strided calls unimplemented, prif_get_raw_strided
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string