prif_get – Caffeine
prif_get Module Procedure
8 statements
Source File
module procedure prif_get module module subroutine prif_get(coarray_handle, coindices, first_element_addr, value, team, team_number, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_intmax_t), intent(in) :: coindices(:)
type(c_ptr), intent(in) :: first_element_addr
type(*), intent(inout), contiguous, target :: value(..)
type(prif_team_type), intent(in), optional :: team
integer(kind=c_intmax_t), intent(in), optional :: team_number
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_get calls prif_image_index, prif_base_pointer, prif_get_raw, caf_as_int, prif_get
prif_image_index calls prif_image_index, prif_num_images
prif_base_pointer calls prif_base_pointer, prif_num_images, assert, caf_convert_base_addr
prif_get_raw calls prif_get_raw, caf_get
prif_num_images calls prif_num_images, caf_num_images
assert calls assert, prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string