prif_co_min – Caffeine
prif_co_min Module Procedure
17 statements
Source File
module procedure prif_co_min module module subroutine prif_co_min(a, result_image, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
type(*), intent(inout), contiguous, target :: a(..)
integer(kind=c_int), intent(in), optional :: result_image
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_co_min calls prif_co_reduce, caf_numeric_type, caf_co_min, caf_is_f_string, optional_value, prif_error_stop, prif_co_min
prif_co_reduce calls prif_co_reduce, caf_is_f_string, optional_value, prif_error_stop, caf_co_reduce, caf_elem_len, assert, caf_same_cfi_type
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_integer, prif_error_stop_character
prif_error_stop_integer calls caf_decaffeinate
assert calls assert, prif_error_stop
prif_error_stop_character calls caf_decaffeinate