prif_end_critical – Caffeine
prif_end_critical Module Procedure
3 statements
Source File
module procedure prif_end_critical module module subroutine prif_end_critical(critical_coarray) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: critical_coarray
Calls
Called by
Contents
None
Call graph
prif_end_critical calls unimplemented, prif_end_critical
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate