prif_put_indirect_with_notify – Caffeine
prif_put_indirect_with_notify Module Procedure
3 statements
Source File
module procedure prif_put_indirect_with_notify module module subroutine prif_put_indirect_with_notify(image_num, remote_ptr, current_image_buffer, size_in_bytes, notify_coarray_handle, notify_offset, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
integer(kind=c_intptr_t), intent(in) :: remote_ptr
type(c_ptr), intent(in) :: current_image_buffer
integer(kind=c_size_t), intent(in) :: size_in_bytes
type(prif_coarray_handle), intent(in) :: notify_coarray_handle
integer(kind=c_size_t), intent(in) :: notify_offset
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_put_indirect_with_notify calls unimplemented, prif_put_indirect_with_notify
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_integer, prif_error_stop_character
prif_error_stop_integer calls caf_decaffeinate
prif_error_stop_character calls caf_decaffeinate