prif_get_context_data – Caffeine
prif_get_context_data Module Procedure
4 statements
Source File
module procedure prif_get_context_data module module subroutine prif_get_context_data(coarray_handle, context_data) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handle
type(c_ptr), intent(out) :: context_data
Calls
Called by
Contents
None
Call graph
prif_get_context_data calls call_assert, unimplemented, coarray_handle_check, prif_get_context_data
unimplemented calls prif_error_stop
coarray_handle_check calls assert_always
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate