prif_image_status – Caffeine
prif_image_status Module Procedure
3 statements
Source File
module procedure prif_image_status impure elemental module module subroutine prif_image_status(image, team, image_status) Interface →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image
type(prif_team_type), intent(in), optional :: team
integer(kind=c_int), intent(out) :: image_status
Calls
Called by
Contents
None
Call graph
prif_image_status calls unimplemented, prif_image_status
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string