prif_ucobound_with_dim – Caffeine
prif_ucobound_with_dim Module Procedure
3 statements
Source File
module procedure prif_ucobound_with_dim module module subroutine prif_ucobound_with_dim(coarray_handle, dim, ucobound) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_int), intent(in) :: dim
integer(kind=c_intmax_t), intent(out) :: ucobound
Calls
Called by
Contents
None
Call graph
prif_ucobound_with_dim calls unimplemented, prif_ucobound_with_dim
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string