prif_stopped_images – Caffeine
prif_stopped_images Module Procedure
3 statements
Source File
module procedure prif_stopped_images module module subroutine prif_stopped_images(team, stopped_images) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_team_type), intent(in), optional :: team
integer(kind=c_int), intent(out), allocatable :: stopped_images(:)
Calls
Called by
Contents
None
Call graph
prif_stopped_images calls unimplemented, prif_stopped_images
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string