prif_num_images – Caffeine
prif_num_images Module Procedure
3 statements
Source File
module procedure prif_num_images module module subroutine prif_num_images(team, team_number, image_count) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_team_type), intent(in), optional :: team
integer(kind=c_intmax_t), intent(in), optional :: team_number
integer(kind=c_int), intent(out) :: image_count
Calls
Called by
Contents
None
Call graph
prif_num_images calls caf_num_images, prif_num_images
prif_base_pointer calls prif_num_images, prif_base_pointer
prif_image_index calls prif_num_images, prif_image_index
prif_get calls prif_base_pointer, prif_image_index, prif_get
prif_put calls prif_base_pointer, prif_image_index, prif_put