prif_change_team – Caffeine
prif_change_team Module Procedure
11 statements
Source File
module procedure prif_change_team module module subroutine prif_change_team(team, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_team_type), intent(in) :: team
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_change_team calls caf_have_child_teams, caf_establish_mspace, caf_this_image, as_c_ptr, caf_establish_child_heap, prif_change_team
caf_establish_child_heap calls caf_this_image, caf_allocate_remaining, prif_co_broadcast, as_int
prif_co_broadcast calls prif_co_broadcast, caf_co_broadcast