prif_deallocate – Caffeine
prif_deallocate Module Procedure
26 statements
Source File
module procedure prif_deallocate module module subroutine prif_deallocate(coarray_handles, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in), target :: coarray_handles(:)
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_deallocate calls prif_sync_all, caf_deallocate, prif_error_stop, remove_from_team_list, caf_this_image, prif_deallocate
prif_sync_all calls prif_sync_all, caf_sync_all
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string