prif_get_strided_indirect – Caffeine
prif_get_strided_indirect Module Procedure
3 statements
Source File
module procedure prif_get_strided_indirect module module subroutine prif_get_strided_indirect(image_num, remote_ptr, remote_stride, current_image_buffer, current_image_stride, element_size, extent, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
integer(kind=c_intptr_t), intent(in) :: remote_ptr
integer(kind=c_ptrdiff_t), intent(in) :: remote_stride(:)
type(c_ptr), intent(in) :: current_image_buffer
integer(kind=c_ptrdiff_t), intent(in) :: current_image_stride(:)
integer(kind=c_size_t), intent(in) :: element_size
integer(kind=c_size_t), intent(in) :: extent(:)
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_get_strided_indirect calls unimplemented, prif_get_strided_indirect
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string