prif_this_image_with_dim – Caffeine
prif_this_image_with_dim Module Procedure
4 statements
Source File
module procedure prif_this_image_with_dim module module subroutine prif_this_image_with_dim(coarray_handle, dim, team, cosubscript) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_int), intent(in) :: dim
type(prif_team_type), intent(in), optional :: team
integer(kind=c_int64_t), intent(out) :: cosubscript
Calls
Called by
Contents
None
Call graph
prif_this_image_with_dim calls call_assert, coarray_handle_check, unimplemented, prif_this_image_with_dim
coarray_handle_check calls assert_always
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate