prif_base_pointer – Caffeine
prif_base_pointer Module Procedure
10 statements
Source File
module procedure prif_base_pointer module module subroutine prif_base_pointer(coarray_handle, image_num, ptr) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_int), intent(in) :: image_num
integer(kind=c_intptr_t), intent(out) :: ptr
Calls
Called by
Contents
None
Call graph
prif_base_pointer calls prif_num_images, assert, caf_convert_base_addr, prif_base_pointer
prif_num_images calls prif_num_images, caf_num_images
assert calls assert, prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string
prif_get calls prif_base_pointer, prif_get
prif_put calls prif_base_pointer, prif_put