prif_co_reduce – Caffeine
prif_co_reduce Module Procedure
164 statements
Source File
module procedure prif_co_reduce module module subroutine prif_co_reduce(a, operation, result_image, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
type(*), intent(inout), contiguous, target :: a(..)
type(c_funptr), value :: operation
integer(kind=c_int), intent(in), optional :: result_image
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_co_reduce calls assert, caf_is_f_string, caf_same_cfi_type, caf_elem_len, optional_value, prif_error_stop, caf_co_reduce, prif_co_reduce
assert calls assert, prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate
prif_co_max calls prif_co_reduce, prif_co_max
prif_co_min calls prif_co_reduce, prif_co_min