prif_fail_image – Caffeine
prif_fail_image Module Procedure
3 statements
Source File
module procedure prif_fail_image module module subroutine prif_fail_image() Interface →
Arguments
None
Calls
Called by
Contents
None
Call graph
prif_fail_image calls unimplemented, prif_fail_image
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_integer, prif_error_stop_character
prif_error_stop_integer calls caf_decaffeinate
prif_error_stop_character calls caf_decaffeinate