prif_event_query – Caffeine
prif_event_query Module Procedure
3 statements
Source File
module procedure prif_event_query module module subroutine prif_event_query(event_var_ptr, count, stat) Interface →
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: event_var_ptr
integer(kind=c_intmax_t), intent(out) :: count
integer(kind=c_int), intent(out), optional :: stat
Calls
Called by
Contents
None
Call graph
prif_event_query calls unimplemented, prif_event_query
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string