prif_lock – Caffeine
prif_lock Module Procedure
3 statements
Source File
module procedure prif_lock module module subroutine prif_lock(image_num, coarray_handle, offset, acquired_lock, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_size_t), intent(in) :: offset
logical(kind=c_bool), intent(out), optional :: acquired_lock
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_lock calls unimplemented, prif_lock
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string