prif_allocate – Caffeine
prif_allocate Module Procedure
31 statements
Source File
module procedure prif_allocate module module subroutine prif_allocate(lcobounds, ucobounds, lbounds, ubounds, element_length, final_func, coarray_handle, allocated_memory, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_intmax_t), intent(in), dimension(:) :: lcobounds
integer(kind=c_intmax_t), intent(in), dimension(:) :: ucobounds
integer(kind=c_intmax_t), intent(in), dimension(:) :: lbounds
integer(kind=c_intmax_t), intent(in), dimension(:) :: ubounds
integer(kind=c_size_t), intent(in) :: element_length
type(c_funptr), intent(in) :: final_func
type(prif_coarray_handle), intent(out) :: coarray_handle
type(c_ptr), intent(out) :: allocated_memory
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_allocate calls caf_as_int, add_to_team_list, caf_as_c_ptr, caf_allocate, caf_this_image, prif_co_sum, prif_allocate
prif_co_sum calls prif_co_sum, optional_value, caf_co_sum