prif_allocate_coarray – Caffeine
prif_allocate_coarray Module Procedure
39 statements
Source File
module procedure prif_allocate_coarray module module subroutine prif_allocate_coarray(lcobounds, ucobounds, lbounds, ubounds, element_size, final_func, coarray_handle, allocated_memory, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_intmax_t), intent(in), dimension(:) :: lcobounds
integer(kind=c_intmax_t), intent(in), dimension(:) :: ucobounds
integer(kind=c_intmax_t), intent(in), dimension(:) :: lbounds
integer(kind=c_intmax_t), intent(in), dimension(:) :: ubounds
integer(kind=c_size_t), intent(in) :: element_size
type(c_funptr), intent(in) :: final_func
type(prif_coarray_handle), intent(out) :: coarray_handle
type(c_ptr), intent(out) :: allocated_memory
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_allocate_coarray calls caf_this_image, caf_deallocate, prif_co_sum, caf_establish_child_heap, as_c_ptr, caf_allocate, as_int, caf_have_child_teams, add_to_team_list, prif_allocate_coarray
prif_co_sum calls prif_co_sum, optional_value, caf_co_sum
caf_establish_child_heap calls caf_this_image, as_int, caf_allocate_remaining, prif_co_broadcast
prif_co_broadcast calls prif_co_broadcast, caf_co_broadcast