prif_atomic_cas_logical – Caffeine
prif_atomic_cas_logical Module Procedure
3 statements
Source File
module procedure prif_atomic_cas_logical module module subroutine prif_atomic_cas_logical(image_num, coarray_handle, offset, old, compare, new, stat) Interface →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_size_t), intent(in) :: offset
logical(kind=prif_atomic_logical_kind), intent(out) :: old
logical(kind=prif_atomic_logical_kind), intent(in) :: compare
logical(kind=prif_atomic_logical_kind), intent(in) :: new
integer(kind=c_int), intent(out), optional :: stat
Calls
Called by
Contents
None
Call graph
prif_atomic_cas_logical calls unimplemented, prif_atomic_cas_logical
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate