prif_co_max – Caffeine
prif_co_max Module Procedure
17 statements
Source File
module procedure prif_co_max module module subroutine prif_co_max(a, result_image, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
type(*), intent(inout), contiguous, target :: a(..)
integer(kind=c_int), intent(in), optional :: result_image
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_co_max calls caf_numeric_type, caf_is_f_string, prif_error_stop, optional_value, caf_co_max, prif_co_reduce, prif_co_max
prif_error_stop calls prif_error_stop, prif_error_stop_character, run_callbacks, prif_error_stop_integer
prif_co_reduce calls prif_co_reduce, caf_is_f_string, prif_error_stop, optional_value, assert, caf_same_cfi_type, caf_elem_len, caf_co_reduce
assert calls assert, prif_error_stop
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate