prif_image_index_with_team_number – Caffeine
prif_image_index_with_team_number Module Procedure
4 statements
Source File
module procedure prif_image_index_with_team_number module module subroutine prif_image_index_with_team_number(coarray_handle, sub, team_number, image_index) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_int64_t), intent(in) :: sub(:)
integer(kind=c_int), intent(in) :: team_number
integer(kind=c_int), intent(out) :: image_index
Calls
Called by
Contents
None
Call graph
prif_image_index_with_team_number calls call_assert, unimplemented, coarray_handle_check, prif_image_index_with_team_number
unimplemented calls prif_error_stop
coarray_handle_check calls assert_always
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate