prif_atomic_fetch_and_indirect – Caffeine
prif_atomic_fetch_and_indirect Module Procedure
3 statements
Source File
module procedure prif_atomic_fetch_and_indirect module module subroutine prif_atomic_fetch_and_indirect(image_num, atom_remote_ptr, value, old, stat) Interface →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
integer(kind=c_intptr_t), intent(in) :: atom_remote_ptr
integer(kind=prif_atomic_int_kind), intent(in) :: value
integer(kind=prif_atomic_int_kind), intent(out) :: old
integer(kind=c_int), intent(out), optional :: stat
Calls
Called by
Contents
None
Call graph
prif_atomic_fetch_and_indirect calls unimplemented, prif_atomic_fetch_and_indirect
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate