prif_deallocate_coarray – Caffeine
prif_deallocate_coarray Module Procedure
33 statements
Source File
module procedure prif_deallocate_coarray module module subroutine prif_deallocate_coarray(coarray_handles, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handles(:)
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_deallocate_coarray calls call_assert, caf_establish_child_heap, caf_deallocate, prif_error_stop, prif_sync_all, coarray_handle_check, remove_from_team_list, caf_have_child_teams, prif_deallocate_coarray
caf_establish_child_heap calls caf_allocate_remaining, as_int, prif_co_broadcast
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_integer, prif_error_stop_character
prif_sync_all calls prif_sync_all, caf_sync_all
coarray_handle_check calls assert_always
prif_co_broadcast calls prif_co_broadcast, caf_co_broadcast
prif_error_stop_integer calls caf_decaffeinate
prif_error_stop_character calls caf_decaffeinate
prif_end_team calls prif_deallocate_coarray, prif_end_team