put_strided_helper – Caffeine
put_strided_helper Subroutine
17 statements
Source File
subroutine put_strided_helper(image_num, remote_ptr, remote_stride, current_image_buffer, current_image_stride, element_size, extent, stat, errmsg, errmsg_alloc)
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
integer(kind=c_intptr_t), intent(in) :: remote_ptr
integer(kind=c_ptrdiff_t), intent(in), target, contiguous :: remote_stride(:)
type(c_ptr), intent(in) :: current_image_buffer
integer(kind=c_ptrdiff_t), intent(in), target, contiguous :: current_image_stride(:)
integer(kind=c_size_t), intent(in) :: element_size
integer(kind=c_size_t), intent(in), target, contiguous :: extent(:)
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
put_strided_helper calls call_assert, caf_put_strided
prif_put_strided_indirect calls put_strided_helper, prif_put_strided_indirect
prif_put_strided calls prif_put_strided_indirect, prif_put_strided