subjob_setup – Caffeine
subjob_setup Function
18 statements
Source File
public function subjob_setup() result(result_)
Arguments
None
Return Value logical
Calls
Contents
None
Call graph
subjob_setup calls prif_sync_all, prif_this_image_no_coarray
prif_sync_all calls prif_sync_all, caf_sync_all
prif_this_image_no_coarray calls prif_this_image_no_coarray