caf_this_image – Caffeine
caf_this_image Interface
151 statements
Source File
interface
Called by
function caf_this_image(team) bind(c)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: team
Return Value integer(kind=c_int)
Description
int caf_this_image();
Call graph
prif_deallocate_coarray calls caf_this_image, caf_establish_child_heap, prif_deallocate_coarray
prif_change_team calls caf_this_image, caf_establish_child_heap, prif_change_team
prif_allocate_coarray calls caf_this_image, caf_establish_child_heap, prif_allocate_coarray
caf_establish_child_heap calls caf_this_image
prif_this_image_no_coarray calls caf_this_image, prif_this_image_no_coarray
prif_form_team calls caf_establish_child_heap, prif_form_team
prif_end_team calls prif_deallocate_coarray, prif_end_team