caf_convert_base_addr – Caffeine
caf_convert_base_addr Interface
179 statements
Source File
interface
Called by
module function caf_convert_base_addr(addr, image) result(ptr) bind(c)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: addr
integer(kind=c_int), intent(in), value :: image
Return Value integer(kind=c_intptr_t)
Call graph
base_pointer calls caf_convert_base_addr
prif_get calls base_pointer, prif_get
prif_get_strided calls base_pointer, prif_get_strided
prif_put calls base_pointer, prif_put
prif_put_strided calls base_pointer, prif_put_strided