caf_error_stop – Caffeine
caf_error_stop Interface
8 statements
Source File
public interface caf_error_stop
Called by
Contents
Subroutines
caf_error_stop_character caf_error_stop_integer
Subroutines
private pure module subroutine caf_error_stop_character(stop_code)
stop all images and provide the stop_code as the process exit status
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: stop_code
private pure module subroutine caf_error_stop_integer(stop_code)
stop all images and provide the stop_code, or 0 if not present, as the process exit status
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: stop_code
Call graph
as_character calls caf_error_stop, as_character
caf_co_reduce calls caf_error_stop, assert, caf_co_reduce
caf_co_max calls caf_error_stop, caf_co_reduce, caf_co_max
assert calls caf_error_stop, assert
caf_co_min calls caf_error_stop, caf_co_reduce, caf_co_min
construct calls caf_error_stop