caf_sync_all – Caffeine
caf_sync_all Interface
151 statements
Source File
interface
Called by
subroutine caf_sync_all() bind(c)
Arguments
None
Description
void caf_sync_all();
Call graph
prif_sync_all calls caf_sync_all, prif_sync_all
prif_deallocate_coarray calls prif_sync_all, prif_deallocate_coarray
prif_end_team calls prif_deallocate_coarray, prif_end_team