caf_allocate – Caffeine
caf_allocate Interface
151 statements
Source File
interface
Called by
function caf_allocate(mspace, bytes) result(ptr) bind(c)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: mspace
integer(kind=c_size_t), intent(in), value :: bytes
Return Value type(c_ptr)
Call graph
prif_allocate calls caf_allocate, prif_allocate
prif_allocate_coarray calls caf_allocate, prif_allocate_coarray