caf_numeric_type – Caffeine
caf_numeric_type Interface
151 statements
Source File
interface
Called by
pure function caf_numeric_type(a) bind(c)
Arguments
Type Intent Optional Attributes Name
type(*), intent(in) :: a(..)
Return Value logical(kind=c_bool)
Description
bool caf_numeric_type(CFI_cdesc_t* a_desc);
Call graph
prif_co_max calls caf_numeric_type, prif_co_max
prif_co_min calls caf_numeric_type, prif_co_min