caf_as_int – Caffeine
caf_as_int Interface
140 statements
Source File
interface
Called by
pure function caf_as_int(ptr) bind(c)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: ptr
Return Value integer(kind=c_intptr_t)
Description
intptr_t caf_as_int(void* ptr);
Call graph
prif_allocate_coarray calls caf_as_int, prif_allocate_coarray
prif_get calls caf_as_int, prif_get
prif_put calls caf_as_int, prif_put