caf_deallocate – Caffeine
caf_deallocate Interface
179 statements
Source File
interface
Called by
subroutine caf_deallocate(mspace, mem) bind(c)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: mspace
type(c_ptr), intent(in), value :: mem
Call graph
prif_allocate_coarray calls caf_deallocate, prif_allocate_coarray
prif_deallocate_coarray calls caf_deallocate, prif_deallocate_coarray
prif_deallocate calls caf_deallocate, prif_deallocate
prif_end_team calls prif_deallocate_coarray, prif_end_team