caf_c_decaffeinate – Caffeine
caf_c_decaffeinate Interface
84 statements
Source File
interface
Called by
public subroutine caf_c_decaffeinate(exit_code) bind(c)
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), value :: exit_code
Description
void c_decaffeinate();
Call graph
inner_caf_error_stop_integer calls caf_c_decaffeinate
caf_decaffeinate calls caf_c_decaffeinate, caf_decaffeinate
caf_stop_character calls caf_c_decaffeinate
caf_stop_integer calls caf_c_decaffeinate