caf_is_f_string – Caffeine
caf_is_f_string Interface
94 statements
Source File
interface
Called by
public pure function caf_is_f_string(a) bind(c)
Arguments
Type Intent Optional Attributes Name
type(*), intent(in) :: a(..)
Return Value logical(kind=c_bool)
Description
bool caf_is_f_string(CFI_cdesc_t* a_desc);
Call graph
prif_co_max calls caf_is_f_string, prif_co_reduce, prif_co_max
prif_co_reduce calls caf_is_f_string, prif_co_reduce
prif_co_min calls caf_is_f_string, prif_co_reduce, prif_co_min