prif_alias_destroy – Caffeine
prif_alias_destroy Interface
798 statements
Source File
interface
Calls
public module module subroutine prif_alias_destroy(alias_handle) Implementation →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: alias_handle
Call graph
prif_alias_destroy calls prif_alias_destroy, call_assert, coarray_handle_check, unimplemented
coarray_handle_check calls assert_always
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate