prif_atomic_ref_int_indirect – Caffeine
prif_atomic_ref_int_indirect Interface
798 statements
Source File
interface
Calls
public module module subroutine prif_atomic_ref_int_indirect(image_num, atom_remote_ptr, value, stat) Implementation →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
integer(kind=c_intptr_t), intent(in) :: atom_remote_ptr
integer(kind=prif_atomic_int_kind), intent(out) :: value
integer(kind=c_int), intent(out), optional :: stat
Call graph
prif_atomic_ref_int_indirect calls prif_atomic_ref_int_indirect, unimplemented
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate