prif_put_with_notify_indirect – Caffeine
prif_put_with_notify_indirect Interface
791 statements
Source File
interface
Calls
public module module subroutine prif_put_with_notify_indirect(image_num, coarray_handle, offset, current_image_buffer, size_in_bytes, notify_ptr, stat, errmsg, errmsg_alloc) Implementation →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_size_t), intent(in) :: offset
type(c_ptr), intent(in) :: current_image_buffer
integer(kind=c_size_t), intent(in) :: size_in_bytes
integer(kind=c_intptr_t), intent(in) :: notify_ptr
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Call graph
prif_put_with_notify_indirect calls prif_put_with_notify_indirect, unimplemented
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string