prif_put_strided_with_notify – Caffeine
prif_put_strided_with_notify Interface
791 statements
Source File
interface
Calls
public module module subroutine prif_put_strided_with_notify(image_num, coarray_handle, offset, remote_stride, current_image_buffer, current_image_stride, element_size, extent, notify_coarray_handle, notify_offset, stat, errmsg, errmsg_alloc) Implementation →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_size_t), intent(in) :: offset
integer(kind=c_ptrdiff_t), intent(in) :: remote_stride(:)
type(c_ptr), intent(in) :: current_image_buffer
integer(kind=c_ptrdiff_t), intent(in) :: current_image_stride(:)
integer(kind=c_size_t), intent(in) :: element_size
integer(kind=c_size_t), intent(in) :: extent(:)
type(prif_coarray_handle), intent(in) :: notify_coarray_handle
integer(kind=c_size_t), intent(in) :: notify_offset
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Call graph
prif_put_strided_with_notify calls prif_put_strided_with_notify, unimplemented
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string