prif_event_wait – Caffeine
prif_event_wait Interface
791 statements
Source File
interface
Calls
public module module subroutine prif_event_wait(event_var_ptr, until_count, stat, errmsg, errmsg_alloc) Implementation →
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: event_var_ptr
integer(kind=c_intmax_t), intent(in), optional :: until_count
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Call graph
prif_event_wait calls prif_event_wait, unimplemented
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string