prif_image_index – Caffeine
prif_image_index Interface
791 statements
Source File
interface
Calls
public module module subroutine prif_image_index(coarray_handle, sub, image_index) Implementation →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_intmax_t), intent(in) :: sub(:)
integer(kind=c_int), intent(out) :: image_index
Call graph
prif_image_index calls prif_image_index, prif_num_images
prif_num_images calls prif_num_images, caf_num_images