prif_sync_images – Caffeine
prif_sync_images Interface
798 statements
Source File
interface
Calls
public module module subroutine prif_sync_images(image_set, stat, errmsg, errmsg_alloc) Implementation →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in), optional :: image_set(:)
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Call graph
prif_sync_images calls prif_sync_images, unimplemented
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate