prif_team_number – Caffeine
prif_team_number Interface
791 statements
Source File
interface
Calls
public module module subroutine prif_team_number(team, team_number) Implementation →
Arguments
Type Intent Optional Attributes Name
type(prif_team_type), intent(in), optional :: team
integer(kind=c_intmax_t), intent(out) :: team_number
Call graph
prif_team_number calls prif_team_number, unimplemented
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string