prif_put_strided – Caffeine
prif_put_strided Interface
798 statements
Source File
interface
Calls
public module module subroutine prif_put_strided(image_num, coarray_handle, offset, remote_stride, current_image_buffer, current_image_stride, element_size, extent, stat, errmsg, errmsg_alloc) Implementation →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_size_t), intent(in) :: offset
integer(kind=c_ptrdiff_t), intent(in) :: remote_stride(:)
type(c_ptr), intent(in) :: current_image_buffer
integer(kind=c_ptrdiff_t), intent(in) :: current_image_stride(:)
integer(kind=c_size_t), intent(in) :: element_size
integer(kind=c_size_t), intent(in) :: extent(:)
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Call graph
prif_put_strided calls prif_put_strided, call_assert, prif_put_strided_indirect, base_pointer, coarray_handle_check
prif_put_strided_indirect calls prif_put_strided_indirect, put_strided_helper
base_pointer calls call_assert, coarray_handle_check, call_assert_describe, caf_convert_base_addr
coarray_handle_check calls assert_always
put_strided_helper calls call_assert, caf_put_strided