prif_atomic_fetch_xor – Caffeine
prif_atomic_fetch_xor Interface
798 statements
Source File
interface
Calls
public module module subroutine prif_atomic_fetch_xor(image_num, coarray_handle, offset, value, old, stat) Implementation →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_size_t), intent(in) :: offset
integer(kind=prif_atomic_int_kind), intent(in) :: value
integer(kind=prif_atomic_int_kind), intent(out) :: old
integer(kind=c_int), intent(out), optional :: stat
Call graph
prif_atomic_fetch_xor calls prif_atomic_fetch_xor, unimplemented
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate