prif_alias_create – Caffeine
prif_alias_create Interface
798 statements
Source File
interface
Calls
public module module subroutine prif_alias_create(source_handle, alias_lcobounds, alias_ucobounds, alias_handle) Implementation →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: source_handle
integer(kind=c_int64_t), intent(in) :: alias_lcobounds(:)
integer(kind=c_int64_t), intent(in) :: alias_ucobounds(:)
type(prif_coarray_handle), intent(out) :: alias_handle
Call graph
prif_alias_create calls prif_alias_create, call_assert, coarray_handle_check, unimplemented
coarray_handle_check calls assert_always
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate