prif_notify_wait – Caffeine
prif_notify_wait Interface
798 statements
Source File
interface
Calls
public module module subroutine prif_notify_wait(notify_var_ptr, until_count, stat, errmsg, errmsg_alloc) Implementation →
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: notify_var_ptr
integer(kind=c_int64_t), intent(in), optional :: until_count
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Call graph
prif_notify_wait calls prif_notify_wait, unimplemented
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate