prif_atomic_cas – Caffeine
prif_atomic_cas Interface
4 statements
Source File
public interface prif_atomic_cas
Calls
Contents
Module Procedures
prif_atomic_cas_int prif_atomic_cas_logical
Module Procedures
private interface prif_atomic_cas_int()
Arguments
None
private interface prif_atomic_cas_logical()
Arguments
None
Call graph
prif_atomic_cas calls prif_atomic_cas_int, prif_atomic_cas_logical
prif_atomic_cas_int calls prif_atomic_cas_int, unimplemented
prif_atomic_cas_logical calls prif_atomic_cas_logical, unimplemented
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string