prif_size_bytes – Caffeine
prif_size_bytes Interface
798 statements
Source File
interface
Calls
public module module subroutine prif_size_bytes(coarray_handle, data_size) Implementation →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_size_t), intent(out) :: data_size
Call graph
prif_size_bytes calls prif_size_bytes, unimplemented
unimplemented calls prif_error_stop
prif_error_stop calls prif_error_stop, run_callbacks, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls caf_decaffeinate
prif_error_stop_integer calls caf_decaffeinate