prif_get_indirect – Caffeine
prif_get_indirect Interface
791 statements
Source File
interface
Calls
Called by
public module module subroutine prif_get_indirect(image_num, remote_ptr, current_image_buffer, size_in_bytes, stat, errmsg, errmsg_alloc) Implementation →
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in) :: image_num
integer(kind=c_intptr_t), intent(in) :: remote_ptr
type(c_ptr), intent(in) :: current_image_buffer
integer(kind=c_size_t), intent(in) :: size_in_bytes
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Call graph
prif_get_indirect calls prif_get_indirect, caf_get
prif_get calls prif_get_indirect, prif_get