prif_put – Caffeine
prif_put Interface
480 statements
Source File
interface
Calls
public module module subroutine prif_put(coarray_handle, cosubscripts, value, first_element_addr, team, team_number, notify_ptr, stat, errmsg, errmsg_alloc) Implementation →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handle
integer(kind=c_intmax_t), intent(in) :: cosubscripts(:)
type(*), intent(in), contiguous, target :: value(..)
type(c_ptr), intent(in) :: first_element_addr
type(prif_team_type), intent(in), optional :: team
integer(kind=c_intmax_t), intent(in), optional :: team_number
integer(kind=c_intptr_t), intent(in), optional :: notify_ptr
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Call graph
prif_put calls prif_put, prif_image_index, prif_base_pointer, caf_as_int, prif_put_raw
prif_image_index calls prif_image_index, prif_num_images
prif_base_pointer calls prif_base_pointer, prif_num_images, assert, caf_convert_base_addr
prif_put_raw calls prif_put_raw, caf_put
prif_num_images calls prif_num_images, caf_num_images
assert calls assert, prif_error_stop
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string