name: Build with LLVM Flang

on: [push, pull_request]


jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: true
    container: gmao/llvm-flang:latest
    env:
      FC: flang-new
      CC: clang

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: fortran-lang/setup-fpm@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Test with LLVM Flang
      if: contains(matrix.os, 'ubuntu')
      run: |
        fpm --version
        $FC --version
        $CC --version
        export FPM_FC=$FC
        export FPM_CC=$CC
        export GASNET_PSHM_NODES=8
        apt update
        apt install -y build-essential pkg-config make
        ./install.sh
