name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  setup: # establish default configuration values, independent of repo/org
    name: Setup
    runs-on: ubuntu-latest
    outputs: 
      # The LLVM Flang version on Homebrew : https://formulae.brew.sh/formula/flang
      BREW_FLANG_VERSION: ${{ steps.vars.outputs.BREW_FLANG_VERSION }}
    steps:
      - name: Set default configuration variables
        id: vars
        run: echo "BREW_FLANG_VERSION=22" >> $GITHUB_OUTPUT

  build:
    name: ${{ matrix.compiler }}-${{ matrix.version || needs.setup.outputs.BREW_FLANG_VERSION }} ${{ matrix.network || '' }} (${{ matrix.os }}) ${{ matrix.label }}
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-15, macos-15-intel, macos-26, macos-26-intel, ubuntu-24.04 ]
        compiler: [ gfortran ]
        version: [ 13, 14, 15 ]
        include:

        # --- flang coverage ---
          - os: macos-14
            compiler: flang
            brew_via_install: 1
          - os: macos-15
            compiler: flang
            brew_via_install: 1
          - os: macos-15-intel
            compiler: flang
            brew_via_install: 1
          - os: macos-26
            compiler: flang
            brew_via_install: 1
          - os: macos-26-intel
            compiler: flang
            brew_via_install: 1

          - os: ubuntu-24.04
            compiler: flang
            label: Homebrew
            brew_via_install: 1

          # https://hub.docker.com/r/snowstep/llvm/tags
          - os: ubuntu-24.04
            compiler: flang
            version: latest
            container: snowstep/llvm:ubuntu-24.04-latest

          # https://hub.docker.com/r/phhargrove/llvm-flang/tags
          - os: ubuntu-24.04
            compiler: flang
            version: 22
            container: phhargrove/llvm-flang:22.1.3-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 21
            container: phhargrove/llvm-flang:21.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 20
            container: phhargrove/llvm-flang:20.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 19
            FFLAGS: -mmlir -allow-assumed-rank
            container: phhargrove/llvm-flang:19.1.1-latest

        # --- lfortran coverage ---

          # https://github.com/lfortran/lfortran/pkgs/container/lfortran
          - os: ubuntu-22.04
            compiler: lfortran
            version: latest
            container: ghcr.io/lfortran/lfortran:latest

          - os: ubuntu-22.04
            compiler: lfortran
            version: 0.63
            container: ghcr.io/lfortran/lfortran:v0.63.0

          # https://hub.docker.com/r/phhargrove/lfortran/tags
          - os: ubuntu-24.04
            compiler: lfortran
            version: 0.63
            container: phhargrove/lfortran:0.63.0-1

        # --- PRIF-old coverage ---
          - os: ubuntu-24.04
            compiler: flang
            version: 21
            label: PRIF-0.5
            FFLAGS: -DFORCE_PRIF_0_5
            container: phhargrove/llvm-flang:21.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 21
            label: PRIF-0.6
            FFLAGS: -DFORCE_PRIF_0_6
            container: phhargrove/llvm-flang:21.1.0-latest

        # --- udp coverage for selected configs ---
          - os: macos-15
            compiler: gfortran
            version: 14
            network: udp

          - os: ubuntu-24.04
            compiler: gfortran
            version: 15
            network: udp
          - os: ubuntu-24.04
            compiler: gfortran
            version: 14
            network: udp

          - os: macos-15-intel
            compiler: flang
            network: udp
          - os: macos-15
            compiler: flang
            network: udp
          - os: macos-26-intel
            compiler: flang
            network: udp
          - os: macos-26
            compiler: flang
            network: udp

          - os: ubuntu-24.04
            compiler: flang
            version: 20
            network: udp
            container: phhargrove/llvm-flang:20.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 21
            network: udp
            container: phhargrove/llvm-flang:21.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 22
            network: udp
            container: phhargrove/llvm-flang:22.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: latest
            network: udp
            container: snowstep/llvm:ubuntu-24.04-latest

    container:
      image: ${{ matrix.container }}

    env:
      COMPILER_VERSION: ${{ matrix.version || needs.setup.outputs.BREW_FLANG_VERSION }}
      NATIVE_MULTI_IMAGE: ${{ matrix.native_multi_image || 
          ( matrix.compiler == 'flang' && ( ! matrix.version || matrix.version >= 22 || matrix.version == 'latest' ) ) 
        }}
      FFLAGS: ${{ matrix.FFLAGS }}
      PREFIX: install
      NETWORK_ARG: ${{ matrix.network && format('--network={0}',matrix.network) || '' }}
      CURL_OPTIONS: -L --retry 10 --retry-all-errors --fail 
      GASNET_CONFIGURE_ARGS: --enable-rpath --enable-debug
      GASNET_SPAWN_VERBOSE: 1
      GASNET_SPAWNFN: L
      GASNET_MASTERIP: 127.0.0.1
      CAF_IMAGES: 8

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    ##########################################################################
    # Establish Dependencies

    - name: Install Ubuntu Container Dependencies
      if: ${{ contains(matrix.os, 'ubuntu') && matrix.container != '' && !contains(matrix.container, 'phhargrove') }}
      run: |
        set -x
        apt update
        apt install -y build-essential pkg-config make git curl

    - name: Install Ubuntu Native Dependencies
      if: ${{ contains(matrix.os, 'ubuntu') && matrix.container == '' && !matrix.brew_via_install }}
      run: |
        set -x
        sudo apt update
        sudo apt install -y build-essential pkg-config make
        if [[ ${COMPILER_VERSION} < 15 ]] ; then \
          sudo apt install -y gfortran-${COMPILER_VERSION} g++-${COMPILER_VERSION} ; \
        else \
          curl $CURL_OPTIONS https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh -o install-homebrew.sh ; \
          chmod +x install-homebrew.sh ; \
          env CI=1 ./install-homebrew.sh ; \
          HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew" ; \
          ${HOMEBREW_PREFIX}/bin/brew install -v gcc@${COMPILER_VERSION} binutils ; \
          ls -al ${HOMEBREW_PREFIX}/bin ; \
          echo "PATH=${HOMEBREW_PREFIX}/bin:${PATH}" >> "$GITHUB_ENV" ; \
          : Homebrew GCC@15 needs binutils 2.44+ ; \
          HOMEBREW_BINUTILS=$(ls -d ${HOMEBREW_PREFIX}/Cellar/binutils/2.*/bin ) ; \
          ls -al ${HOMEBREW_BINUTILS} ; \
          echo "FFLAGS=${FFLAGS:+"$FFLAGS" }-B ${HOMEBREW_BINUTILS}" >> "$GITHUB_ENV" ; \
          echo "CFLAGS=${CFLAGS:+"$CFLAGS" }-B ${HOMEBREW_BINUTILS}" >> "$GITHUB_ENV" ; \
          echo "CXXFLAGS=${CXXFLAGS:+"$CXXFLAGS" }-B ${HOMEBREW_BINUTILS}" >> "$GITHUB_ENV" ; \
          echo "LDFLAGS=${LDFLAGS:+"$LDFLAGS" }-B ${HOMEBREW_BINUTILS}" >> "$GITHUB_ENV" ; \
        fi

    - name: Install macOS Dependencies
      if: ${{ contains(matrix.os, 'macos') && !matrix.brew_via_install }}
      run: |
        set -x
        brew update
        # fpm binary distribution for macOS requires gfortran shared libraries from gcc@12
        brew install gcc@12

    - name: Install LLVM flang on macOS
      if: ${{ contains(matrix.os, 'macos') && matrix.compiler == 'flang' && !matrix.brew_via_install }}
      run: |
        set -x
        brew install llvm@${COMPILER_VERSION} flang
        # Prepend homebrew clang to PATH:
        echo "PATH=$(brew --prefix)/opt/llvm/bin:${PATH}" >> "$GITHUB_ENV"

    - name: Setup FPM
      if: ${{ !matrix.brew_via_install }}
      uses: fortran-lang/setup-fpm@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fpm-version: latest

    - name: Build FPM
      if: false
      run: |
        set -x
        export FPM_VERSION=0.12.0
        curl --retry 5 -LOsS https://github.com/fortran-lang/fpm/releases/download/v$FPM_VERSION/fpm-$FPM_VERSION.F90
        mkdir fpm-temp
        gfortran-14 -o fpm-temp/fpm fpm-$FPM_VERSION.F90
        echo "PATH=${PWD}/fpm-temp:${PATH}" >> "$GITHUB_ENV"

    ##########################################################################
    # Set Install Variables

    - name: Set gfortran variables
      if: matrix.compiler == 'gfortran'
      run: |
        set -x
        echo "FC=gfortran-${COMPILER_VERSION}" >> "$GITHUB_ENV"
        echo "CC=gcc-${COMPILER_VERSION}" >> "$GITHUB_ENV"
        echo "CXX=g++-${COMPILER_VERSION}" >> "$GITHUB_ENV"
        # XCode 26 / gfortran bug workaround
        if [[ ${{ matrix.os }} =~ macos-26 ]] ; then \
          echo "GASNET_CONFIGURE_ARGS=$GASNET_CONFIGURE_ARGS --enable-force-posix-realtime" >> "$GITHUB_ENV" ; \
        fi

    - name: Set flang variables
      if: ${{ matrix.compiler == 'flang' }}
      run: |
        set -x
        if [ -z "${{ matrix.brew_via_install }}" ] ; then
          echo "FC=flang-new" >> "$GITHUB_ENV" 
          echo "CC=clang" >> "$GITHUB_ENV"
          echo "CXX=clang++" >> "$GITHUB_ENV"
        fi
        if [ "${NATIVE_MULTI_IMAGE}" == true ] ; then
          echo "FFLAGS=$FFLAGS -fcoarray" >> "$GITHUB_ENV"
        fi

    - name: Setup lfortran dependencies and variables
      if: ${{ matrix.compiler == 'lfortran' }}
      run: |
        set -x
        apt update
        apt install -y llvm clang
        if [ ${{ contains(matrix.container, 'ghcr.io/lfortran') }} = true ]; then
          ls -alR /app 
          # Add container lfortran to PATH:
          PATH="/app/bin:$PATH"
          echo "/app/bin" >> "$GITHUB_PATH" 
        fi
        echo "FC=lfortran" >> "$GITHUB_ENV" 
        echo "CC=clang" >> "$GITHUB_ENV"
        echo "CXX=clang++" >> "$GITHUB_ENV"
        HEADER_NAME=ISO_Fortran_binding.h
        HEADER_TARGET=include/$HEADER_NAME
        HEADER_SOURCE=$(lfortran --print-c-include-dir)/$HEADER_NAME 
        echo "#include <$HEADER_SOURCE>" > $HEADER_TARGET
        find / -name $HEADER_NAME -exec ls -al {} \; -exec md5sum {} \; -exec head {} \; -exec echo --- \;

    - name: Set Caffeine variables
      run: |
        set -x
        # docker instances cannot handle high levels of subjob parallelism
        if test -n "${{ matrix.container }}"; then \
          echo "SUBJOB_PREFIX=CAF_IMAGES=2" >> "$GITHUB_ENV" ; \
        fi
        # disable shared-memory bypass with network=udp to simulate multi-node runs
        if test "${{ matrix.network }}" = "udp"; then \
          echo "GASNET_SUPERNODE_MAXSIZE=1" >> "$GITHUB_ENV" ; \
        fi
        # Turn some knobs for a compiler that natively uses PRIF for multi-image features:
        # HAVE_MULTI_IMAGE : controls app/native-multi-image and prif_init testing
        # HAVE_MULTI_IMAGE_SUPPORT : force-enable Julienne's multi-image support
        if [ "${NATIVE_MULTI_IMAGE}" == true ] ; then
          echo "FFLAGS=$FFLAGS -DHAVE_MULTI_IMAGE -DHAVE_MULTI_IMAGE_SUPPORT" >> "$GITHUB_ENV" ; \
        fi

    ##########################################################################
    # Caffeine Install

    - name: Version info (pre-build)
      run: |
        echo == TOOL VERSIONS ==
        echo Platform version info:
        uname -a
        if test -r /etc/os-release ; then grep -e NAME -e VERSION /etc/os-release  ; fi
        if test -x /usr/bin/sw_vers ; then /usr/bin/sw_vers ; fi
        echo
        echo PATH="$PATH"
        for tool in ${FC} ${CC} ${CXX} fpm ; do
          if command -v $tool > /dev/null 2>&1 ; then
            ( echo ; set -x ; w=$(which $tool) ; ls -al $w ; ls -alhL $w ; $tool --version )
          fi
        done

    - name: Build Caffeine (install.sh)
      run: |
        for var in FC CC CXX FFLAGS CPPFLAGS CFLAGS CXXFLAGS LDFLAGS LIBS GASNET_CONFIGURE_ARGS ; do \
            eval echo "$var=\$$var"; done
        set -x
        ./install.sh --prefix=${PREFIX} ${NETWORK_ARG} --verbose

    ##########################################################################
    # Caffeine Testing

    - name: Version info (run-fpm)
      run: |
        ./run-fpm.sh info

    - name: Run examples
      run: |
        echo CAF_IMAGES=${CAF_IMAGES}
        set -x
        ./run-fpm.sh run --verbose --example hello

    - name: Run native multi-image test
      if: ${{ env.NATIVE_MULTI_IMAGE == 'true' }}
      run: |
        set -x ; ./run-fpm.sh run --verbose 2>&1 | tee output ; \
          test ${PIPESTATUS[0]} = 0 && \
               ! grep -q "IEEE arithmetic exceptions signaled" output

    - name: Run unit tests
      run: |
        echo SUBJOB_PREFIX=${SUBJOB_PREFIX}
        while (( CAF_IMAGES > 0 )); do \
          echo CAF_IMAGES=${CAF_IMAGES} ; \
          ( set -x ; ./run-fpm.sh test --verbose -- ) ; \
          sleep 1 ; \
          CAF_IMAGES=$(( CAF_IMAGES / 2 )) ; \
        done

    - name: Run exit/failure tests
      run: |
        echo CAF_IMAGES=${CAF_IMAGES}
        set -x
        ./run-fpm.sh run --verbose --example stop_with_no_code
        ( set +e ; ./run-fpm.sh run --verbose --example stop_with_integer_code ; test $? = 99 )
        ( set +e ; ./run-fpm.sh run --verbose --example error_stop_with_integer_code ; test $? = 100 )
        ( set +e ; \
          export CAF_IMAGES=1; \
          ./run-fpm.sh run --verbose --example fail_image 2>&1 | tee output ; \
          test ${PIPESTATUS[0]} > 0 && grep -q "FAIL IMAGE" output \
        )
        ( set +e ; \
          ./run-fpm.sh run --verbose --example out_of_memory 2>&1 | tee output ; \
          test ${PIPESTATUS[0]} > 0 && grep -q "out of memory" output \
        )
        ( set +e ; \
          ./run-fpm.sh run --verbose --example out_of_memory -- --coarray 2>&1 | tee output ; \
          test ${PIPESTATUS[0]} > 0 && grep -q "out of memory" output \
        )
        unset GASNET_SPAWN_VERBOSE
        for ((i=1; i<=4; i++)); do \
         (set +e ; \
          ./run-fpm.sh run --verbose --example exit_case -- $i 2>&1 | tee output ; \
          test ${PIPESTATUS[0]} = $((i + 100)) \
            && grep -q "stdout from image $CAF_IMAGES" output \
            && grep -q "stderr from image $CAF_IMAGES" output \
         ) ; \
        done

    - name: Build and Test Caffeine (thread-safe)
      run: |
        for var in FC CC CXX FFLAGS CPPFLAGS CFLAGS LDFLAGS LIBS GASNET_CONFIGURE_ARGS ; do \
            eval echo "$var=\$$var"; done
        set -x
        ./install.sh --prefix=${PREFIX} ${NETWORK_ARG} --enable-threads --verbose
        ./run-fpm.sh test --verbose --

